### ISSUE TITLE
GCC 4.7 and Eigen 3 problem?

### ISSUE THREAD

**Issue by flikka** [OPM/opm-autodiff#157] opened 2014-06-19 11:06 UTC
The test AutoDiffBlockTest failed with GCC 4.7 on Debian. Here is a link to information: https://gist.github.com/flikka/e446fcd15f42e9d2f032

I don't think it is our fault, but I put it in here as a reminder, if someone else gets this problem.

**Comment by atgeirr** [comment] 2015-04-08 07:39
Postponing this as we will not devote time to fix it for the 2015.04 release.

**Comment by atgeirr** [comment] 2015-10-09 15:37
Closing this as it probably was the compiler's fault, and the compiler with the problem is no longer supported by OPM.

**Closed by atgeirr** 2015-10-09 15:37 UTC
