### ISSUE TITLE
sim_fibo_ad(_cp): Well treatment differs between Ug and CpGrid

### ISSUE THREAD

**Issue by blattms** [OPM/opm-autodiff#300] opened 2015-02-11 12:05 UTC
With the current master the results when using different grids differ. Apparently, when using CpGrid the well_control does not get switched. E.g. for SPE1:

```
--- ug.master   2015-02-11 12:55:31.803519032 +0100
+++ cp.master   2015-02-11 12:49:02.127530545 +0100
@@ -44,11 +44,10 @@
 
 Iter    MB(OIL)  MB(WATER)    MB(GAS)       CNVW       CNVO       CNVG  WELL-FLOW WELL-CNTRL
    0  0.000e+00  1.765e-06  8.493e-07  0.000e+00  3.478e-04  8.704e-04  3.232e+01  0.000e+00
-Switching control mode for well INJECTOR from SURFACE_RATE to RESERVOIR_RATE
-   1  8.294e-09  7.539e-07  2.280e-05  1.678e-06  1.298e-03  8.395e-03  4.720e+00  7.105e-15
-   2  1.008e-09  6.650e-09  7.774e-09  4.531e-08  6.367e-07  7.368e-06  3.671e-03  0.000e+00
-   3  3.132e-12  2.220e-11  1.159e-11  1.186e-10  8.281e-10  4.702e-10  7.319e-09  0.000e+00
-Fully implicit solver took: 0.433245 seconds.
+   1  8.295e-09  7.536e-07  2.280e-05  1.677e-06  1.298e-03  8.395e-03  4.720e+00  0.000e+00
+   2  1.028e-09  6.265e-08  4.349e-08  4.508e-08  3.511e-05  1.814e-05  3.698e-03  0.000e+00
+   3  1.928e-11  1.421e-10  7.338e-11  1.013e-09  7.290e-09  3.753e-09  1.416e-08  0.000e+00
+Fully implicit solver took: 0.427339 seconds.
 
 
 ---------------    Simulation step number 1    ---------------
@@ -58,19 +57,19 @@
 
 
 Iter    MB(OIL)  MB(WATER)    MB(GAS)       CNVW       CNVO       CNVG  WELL-FLOW WELL-CNTRL
-   0  2.793e-12  8.786e-04  1.328e-03  1.047e-09  4.777e-01  6.101e-01  7.319e-09  0.000e+00
+   0  2.793e-12  8.786e-04  1.328e-03  1.047e-09  4.777e-01  6.101e-01  1.416e-08  0.000e+00
    1  1.436e-07  1.019e-05  1.284e-03  4.741e-06  1.645e-01  4.242e-01  3.319e+01  0.000e+00
-   2  2.961e-07  1.423e-03  4.962e-05  4.560e-06  6.594e-01  6.994e-02  3.769e+00  0.000e+00
-   3  2.029e-07  1.112e-05  3.416e-05  3.283e-06  2.112e-01  4.190e-01  4.174e+00  0.000e+00
+   2  2.962e-07  1.423e-03  4.965e-05  4.557e-06  6.594e-01  6.993e-02  3.767e+00  0.000e+00
+   3  2.029e-07  1.112e-05  3.410e-05  3.283e-06  2.112e-01  4.190e-01  4.175e+00  0.000e+00
  Oscillating behavior detected: Relaxation set to 0.9
    4  2.540e-07  1.190e-03  1.841e-03  3.229e-06  5.557e-01  6.091e-01  3.158e+01  0.000e+00
-   5  2.152e-08  6.751e-04  4.685e-04  1.052e-04  1.218e-01  6.853e-02  9.503e-01  0.000e+00
+   5  2.150e-08  6.751e-04  4.685e-04  1.052e-04  1.218e-01  6.852e-02  9.503e-01  0.000e+00
    6  5.042e-08  7.882e-05  7.664e-05  9.890e-06  7.001e-03  1.945e-02  7.144e-02  0.000e+00
    7  3.876e-09  7.901e-06  9.142e-06  1.005e-06  7.387e-04  2.055e-03  8.090e-03  0.000e+00
-   8  7.142e-11  7.863e-07  9.356e-07  1.047e-07  7.414e-05  2.069e-04  8.617e-04  0.000e+00
-   9  5.846e-11  7.825e-08  9.419e-08  1.089e-08  7.391e-06  2.073e-05  9.126e-05  0.000e+00
-  10  1.112e-11  7.769e-09  9.486e-09  1.134e-09  7.370e-07  2.075e-06  9.668e-06  0.000e+00
-Fully implicit solver took: 1.65051 seconds.
+   8  7.143e-11  7.863e-07  9.356e-07  1.047e-07  7.414e-05  2.069e-04  8.617e-04  0.000e+00
+   9  5.846e-11  7.826e-08  9.419e-08  1.089e-08  7.391e-06  2.073e-05  9.126e-05  0.000e+00
+  10  1.112e-11  7.769e-09  9.486e-09  1.134e-09  7.371e-07  2.075e-06  9.668e-06  0.000e+00
+Fully implicit solver took: 1.58618 seconds.
 ```

From first observations CpGrid does not detect broken constraints at https://github.com/OPM/opm-autodiff/blob/2f632bc9c3157d9a8e26c6528175e2996f3bea65/opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp#L1135

**Comment by blattms** [comment] 2015-02-11 14:31
This appears to be a floating point issue in the comparisons done at  https://github.com/OPM/opm-autodiff/blob/2f632bc9c3157d9a8e26c6528175e2996f3bea65/opm/autodiff/FullyImplicitBlackoilSolver_impl.hpp#L1061-L1086 
Basically the computed rate is the same as the target up to rounding/representation errors which causes different treatment.

For the first step the picture is:
```
CpGrid: target=32.77412800000000459 computed rate=32.77412800000000459
UG:       target=32.77412800000000459 computed rate=32.774128000000011696
```
Maybe we should add/substract an epsilon during the comparison?

**Comment by atgeirr** [comment] 2015-02-12 14:52
I think I have found the cause of this strange difference in behaviour: a bug in opm-parser in treating GAS RESV limits. Will post an issue there.

**Comment by blattms** [comment] 2015-02-12 15:21
Great!

**Comment by andlaus** [comment] 2015-02-12 15:55
> I think I have found the cause of this strange difference in behaviour: a bug in opm-parser in treating GAS RESV limits. Will post an issue there.

parser bugs aside, shouldn't the simulator codes be more resistant to such "numerical noise"?

**Comment by atgeirr** [comment] 2015-02-12 16:28
Without claiming to have fully untangled this, I think that with two limits that are essentially the same, one may experience things like this, but we'll see.

**Comment by andlaus** [comment] 2015-02-12 17:49
ok, if I understood you correctly, your point is that although the well controls are different, the results are still the same? If that is the case, I suppose there isn't any issue in the first place. @blattms: did you also observe differences in the results? (i.e., in the BHPs and the well rates of the incriminating wells.)

**Comment by atgeirr** [comment] 2015-03-25 13:59
This has been resolved as coming from the (fixed) RESV bug, closing. There may be other differences between the simulators, feel free to open new issues with specifics.

**Closed by atgeirr** 2015-03-25 13:59 UTC
Labels: bug
